services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=crm
    env_file:
      - pg_password.env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=crm
      - DB_USER=postgres
    env_file:
      - pg_password.env
    volumes:
      - uploads:/app/uploads
    depends_on:
      - db
volumes:
  pgdata:
  uploads:
